# Generated by Django 3.2.4 on 2021-07-05 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('Ação', 'Ação'), ('Animação', 'Animação'), ('Aventura', 'Aventura'), ('Comédia', 'Comédia'), ('Drama', 'Drama'), ('Documentário', 'Documentário'), ('Fantasia', 'Fantasia'), ('Ficção', 'Ficção científica'), ('Horror', 'Horror'), ('Musical', 'Musical'), ('Romance', 'Romance'), ('Suspense', 'Suspense'), ('Terror', 'Terror'), ('Outro', 'Outro')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produtora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('1', '21st Century Fox'), ('2', 'DreamWorks'), ('3', 'MGM'), ('4', 'The Weinstein Company'), ('5', 'Lions Gate Entertainment'), ('6', 'Paramount Motion Pictures Group'), ('7', 'Universal Pictures'), ('8', 'The Walt Disney Company'), ('9', 'Time Warner'), ('10', 'Sony Pictures Entertainment'), ('11', 'Outro')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('duracao', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('lancamento', models.IntegerField()),
                ('capa', models.ImageField(blank=True, upload_to='images/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.categoria')),
                ('produtora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.produtora')),
            ],
        ),
    ]
